#!/usr/bin/env python

import webbrowser
import os
import urllib
import sys

comics = {
          "Housepets!"            
            : { 
                'url'       : 'http://www.housepetscomic.com/', 
                'invariant' : 'http://feeds.feedburner.com/housepetscomic/NsPL'
            },
          "Bear Nuts"             
            : {
                'url'       : 'http://www.bearnutscomic.com/', 
                'invariant' : 'http://www.bearnutscomic.com/feed/'                
            },
                
          "Questionable Content"  
            : {
                'url'       : 'http://www.questionablecontent.net/', 
                'invariant' : 'http://www.questionablecontent.net/QCRSS.xml'
            },
          "TwoKinds"              
            : {
                'url'       : 'http://2kinds.com/', 
                'invariant' : 'http://twokinds.keenspot.com/rss.php'
            },
          "Sequential Art"        
            : {
                'url'       
                      : 'http://www.collectedcurios.com/sequentialart.php', 
                'invariant' 
                      : 'http://www.collectedcurios.com/sequentialart.php'  
            },
          "The Less Than Epic Adventures of TJ and Amal" 
            : {
                'url'       : 'http://tjandamal.com/comic/', 
                'invariant' : 'http://feeds.feedburner.com/tjandamal'
            },
          "Boy in the Pink Earmuffs"
            : {
                'url'       : 'http://www.boyinpinkearmuffs.com/', 
                'invariant' : 'http://www.boyinpinkearmuffs.com/feed/'            
            },
          "XKCD"
            : {
                'url'       : 'http://xkcd.com/', 
                'invariant' : 'http://xkcd.com/rss.xml'
            },
          "Oglaf"
            : {
                'url'       : 'http://www.oglaf.com/',
                'invariant' : 'http://www.oglaf.com/feeds/rss/'
            },
          "Girls with Slingshots"
            : {
                'url'       : 'http://www.girlswithslingshots.com/',
                'invariant' :
                            'http://feeds.feedburner.com/Girls_With_Slingshots'
            }
         }

home = os.getenv("HOME")
cacheDir = home + '/.comics-cache/';

try:
  os.mkdir(cacheDir)
except OSError:
  pass

for comic in comics:
  oldFile = cacheDir + comic
  oldText = ''
  try:
    oldText = open(oldFile).read()
  except IOError:
    pass
  try:
    currentText = urllib.urlopen(comics[comic]['invariant']).read()
  except IOError:
    print "Unable to load comics."
    print "Check your internet connection."
    sys.exit(-1)

  if currentText != oldText:

    savout = os.dup(1)
    saverr = os.dup(2)
    os.close(1)
    os.close(2)
    os.open(os.devnull, os.O_RDWR)
    try:
      webbrowser.open_new_tab(comics[comic]['url'])
    finally:
      os.dup2(savout, 1)
      os.dup2(saverr, 2)
    f = open(oldFile, 'w')
    f.write(currentText)
    f.close()
    print comic, "has been updated."
