#!/usr/bin/env python3

import webbrowser
import os
import urllib.request
import sys
import feedparser
import gzip
import io

comics = {
    "Housepets!": {
        'url': 'http://www.housepetscomic.com/',
        'invariant': 'http://feeds.feedburner.com/housepetscomic/NsPL'
    },
    "Bear Nuts": {
        'url': 'http://www.bearnutscomic.com/',
        'invariant': 'http://www.bearnutscomic.com/feed/'
    },
    "Questionable Content": {
        'url': 'http://www.questionablecontent.net/',
        'invariant': 'http://www.questionablecontent.net/QCRSS.xml'
    },
    "TwoKinds": {
        'url': 'http://2kinds.com/',
        'invariant': 'http://twokinds.keenspot.com/rss.php'
    },
    "The Less Than Epic Adventures of TJ and Amal": {
        'url': 'http://tjandamal.com/comic/',
        'invariant': 'http://feeds.feedburner.com/tjandamal'
    },
    "Boy in the Pink Earmuffs": {
        'url': 'http://www.boyinpinkearmuffs.com/',
        'invariant': 'http://www.boyinpinkearmuffs.com/feed/'
    },
    "XKCD": {
        'url': 'http://xkcd.com/',
        'invariant': 'http://xkcd.com/rss.xml'
    },
    "Oglaf": {
        'url': 'http://www.oglaf.com/',
        'invariant': 'http://www.oglaf.com/feeds/rss/'
    },
    "Girls with Slingshots": {
        'url': 'http://www.girlswithslingshots.com/',
        'invariant': 'http://feeds.feedburner.com/Girls_With_Slingshots'
    }
}

home = os.getenv("HOME")
cacheDir = home + '/.comics-cache/'

try:
    os.mkdir(cacheDir)
except OSError:
    pass

for comic in comics:
    oldFile = cacheDir + comic
    oldRSS = feedparser.parse('')
    try:
        oldRSS = feedparser.parse(open(oldFile).read())
    except (IOError, UnicodeDecodeError):
        pass

    headers = {}
    headers['Accept-Encoding'] = 'gzip'
    headers['User-Agent'] = (
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) '
        'Chrome/35.0.1916.47 Safari/537.36')
    req = urllib.request.Request(comics[comic]['invariant'], data=None, headers=headers)
    try:
        response = urllib.request.urlopen(req)
        if response.info().get('Content-Encoding') == 'gzip':
            f = gzip.GzipFile(fileobj=response)
            currentSite = f.read().decode('utf-8')
        else:
            currentSite = response.read().decode('utf-8')
        currentRSS = feedparser.parse(currentSite)
    except IOError as e:
        print("Unable to load comic:", comic)
        print("Error:", e)
        sys.exit(-1)

    if currentRSS != oldRSS:
        savout = os.dup(1)
        saverr = os.dup(2)
        os.close(1)
        os.close(2)
        os.open(os.devnull, os.O_RDWR)
        try:
            webbrowser.open_new_tab(comics[comic]['url'])
        finally:
            os.dup2(savout, 1)
            os.dup2(saverr, 2)
        f = open(oldFile, 'w')
        f.write(currentSite)
        f.close()
        print(comic, "has been updated.")
