#!/bin/bash

# Copy clipboard to secondary
xclip -sel clip -o | xclip -sel secondary

pass=$(lpass show "Dev100" | grep Password | cut -d':' -f2 | tr -d '\n')
echo -n $pass | xclip -sel clip

echo "The password has been copied to your clipboard. You have 10 seconds to paste it"

# Restore secondary back to clipboard
(sleep 10 && xclip -sel secondary -o | xclip -sel clip)&
