#!/usr/bin/env python

import datetime
import os
import subprocess
import re

now = datetime.datetime.now()
fileName = '_posts/' + now.strftime('%Y-%m-%d') + "-notes.markdown"
pathy = os.getcwd().split('/')
className = pathy[-2] + " " + pathy[-1]
if not os.path.exists(fileName):
  previousFile = None
  for fn in sorted(os.listdir('_posts')):
    if re.match('[0-9]{4}-[0-9]{2}-[0-9]{2}', fn):
      previousFile = fn
  if previousFile == None:
    lec = "Lecture 1"
  else:
    f = open('_posts/' + previousFile, 'r')
    f.readline()
    f.readline()
    match = re.search('title: .* Lecture ([0-9]+)',  f.readline())
    f.close()
    lec = "Lecture " + str(int(match.group(1)) + 1)
  
  f = open(fileName, 'w')
  f.write('---\n')
  f.write('layout: notes\n')
  f.write('title: ' + className + " " + lec + "\n")
  f.write('topic:\n')
  f.write('---\n\n')
  f.close()
subprocess.call(['vim', '-cset spell', fileName, '+'])
subprocess.call(['git', 'add', fileName])

message = raw_input('What topic are you talking about? ')

if message == '':
  subprocess.call(['git', 'commit', '-mNotes for ' + className + ' ' + str(now)])
else:
  subprocess.call(['git', 'commit', '-mNotes on ' + message])

